name: ci

on:
  pull_request: {}
  pull_request_review:
    types: [submitted]

jobs:
  waiting-for-approval:
    if: ${{ github.event.review.state != 'approved' }}
    runs-on: actions-runner
    steps:
      - name: Waiting for approval
        run: exit 1

  build:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: actions-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build-action
        uses: ./.github/build-action
        with:
          push: false
