name: ci

on:
  push:
    branches:
      - "prod"

jobs:
  build:
    runs-on: actions-runner
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Skip build if registry already has commit hash tagged
      - name: Build and push
        id: docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/wappuradio/webbi:${{ github.ref_name }}
            ghcr.io/wappuradio/webbi:${{ github.sha }}

    outputs:
      image: ghcr.io/wappuradio/webbi@${{ steps.docker.outputs.digest }}

  deploy:
    runs-on: actions-runner
    needs: build
    environment:
      name: prod
      url: https://wappuradio.fi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASE64 }}

      - run: cat deployment.yaml | sed 's;IMAGE;${{ needs.build.outputs.image }};' | sed 's/ENV/prod/' | kubectl apply -n webbi-prod -f -
