name: ci

on:
  push:
    branches:
      - "prod"

jobs:
  build:
    runs-on: actions-runner
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if commit already pushed to registry
        id: check_registry
        run: >
          curl
            -Ss
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            https://ghcr.io/v2/wappuradio/webbi/tags/list
          | python3
            -c "import sys; import json; sys.argv[1] in json.load(sys.stdin)['tags'] and print('exists=true') or print('exists=false')"
            "${{ github.sha }}"
            >> $GITHUB_OUTPUT

      - name: Build and push
        if: steps.check_registry.outputs.exists == 'false'
        id: docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/wappuradio/webbi:${{ github.ref_name }}
            ghcr.io/wappuradio/webbi:${{ github.sha }}

    outputs:
      image: ghcr.io/wappuradio/webbi:${{ github.sha }}

  deploy:
    runs-on: actions-runner
    needs: build
    environment:
      name: prod
      url: https://wappuradio.fi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASE64 }}

      - run: cat deployment.yaml | sed 's;IMAGE;${{ needs.build.outputs.image }};' | sed 's/ENV/prod/' | kubectl apply -n webbi-prod -f -
