name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: actions-runner
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/wappuradio/webbi:master
    outputs:
      image: ghcr.io/wappuradio/webbi@${{ steps.docker.outputs.digest }}

  deploy:
    runs-on: actions-runner
    needs: build
    environment: 
      name: test
      url: https://webbi-test.wappuradio.fi
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASE64 }}

      - run: cat deployment.yaml | sed 's;IMAGE;${{ needs.build.outputs.image }};' | sed 's/ENV/test/' | kubectl apply -n webbi-test -f -
        env:
          KUBECONFIG: "/home/runner/.kube/config"
